name: Using a Hello World github action Workflow

on:  
  [push]

jobs: 
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JS Action
        id: greeting
        uses: actions/hello-world-javascript-action@main
        with: 
          who-to-greet: Homer Simpson
      - name: Log out greeting
        run: echo ${{steps.greeting.outputs.time}}
