name: Using a Hello World github action Workflow

on:  
  schedule:
    - cron 2 * * * *


jobs: 
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@main
        with: 
          who-to-greet: Homer Simpson
      - name: Log out greeting
        run: echo "Greeting time - ${{steps.greet.outputs.time}}"
