name: Say Hello Homer

on: [push]

jobs: 

  sayhello: 

    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v2

      - name: Say Hello
        run: echo Hello, Homer how are you!
